//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTful_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Parent
    {
        public int ParentId { get; set; }
        public int FamilyId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
    
        public virtual Family Family { get; set; }
    }
}
